######################################################################
# Automatically generated by qmake (3.1) Wed Mar 22 19:25:15 2017
######################################################################

TEMPLATE = app
TARGET = EncryptedMessaging

QT += core gui
QT += widgets

# Input
SOURCES += main.cpp
